package edu.umg.utils;

public enum ErrorCode {
    CONFIGURACION_PUERTO_INVALIDO,
    NO_CONEXION_DB,
    NO_EXISTE_ARCHIVO,
    SUPERA_LIMITE_ARREGLO,
    TAMANIO_MINIMO,
    ERROR_INDICE_ARREGLO
}
